# Generated by Django 6.0.6 on 2026-06-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.IntegerField(default=10),
        ),
    ]
